### ISSUE TITLE
Match full at-mentions

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/hubot-group#2]
Currently, saying "@bar" will match groups @b, @ba, and @bar.
Also, saying "asdf@gmail.com" will match groups @g, @gm, @gma, ..., @gmail.com.

This is undesired behavior - we should only match full words. Sticking word boundaries (`\b`) in the search regex should fix the problem.

**Comment by bar** [comment]
@anishathalye why me?

**Comment by anishathalye** [comment]
Whoops, when writing the issue, I didn't realize that I'd actually tag a bunch of random people. Sorry about that!
(this is why the name: btw; https://en.wikipedia.org/wiki/Foobar#Usage_in_code)

**Comment by anishathalye** [comment]
Fixed in adce2365b362b6417a7bc40b0907358bee1ee758.
