### ISSUE TITLE
Add original message to notification

### ISSUE THREAD

**Issue by eddywashere** [anishathalye/hubot-group#3]
Right now, when someone uses an @group mention in slack, if I'm mentioned, I'll only get an email/notification with just the group usernames. It would be nice to include the original message for more context. Great for that reason, but not so much for people who are already in the chat room.

Would you be open to a pr adding a configuration variable `HUBOT_GROUP_PREPEND_MSG`?

**Comment by anishathalye** [comment]
Great idea! If you want to implement it, feel free to go ahead and do that, otherwise, I'll get to it soon.

**Comment by anishathalye** [comment]
Fixed in bd9b6be0b4f1cd6eb1333d85ae0b1f5f69e0993a / v1.4.0.
