### ISSUE TITLE
Add/tag users by unique id.

### ISSUE THREAD

**Issue by Detry322** [anishathalye/hubot-group#6]
The hubot brain identifies each user by a unique ID. It would be nice if when you added someone to the group, it instead adds their unique ID to the group, so that when you ping someone who changes their name, it still shows up as a ping

**Comment by anishathalye** [comment]
Worth doing at some point. I'm not sure if the API exposes these IDs, and I'm not sure if this would work with other chat services that people use Hubot with (e.g. Campfire).

**Comment by anishathalye** [comment]
superseded by #11
