### ISSUE TITLE
Not saving data post restart.

### ISSUE THREAD

**Issue by D0cR3d** [anishathalye/hubot-group#7]
I'm not sure if I'm doing something wrong, but whenever I restart the bot it's not saving the data. I'm new to hubot and this hubot-group plugin, so I'm not sure if it's not actually saving anything, or if I've done anything wrong. I'm not even really sure where to start. Any help would be appreciated.

**Comment by anishathalye** [comment]
Are you using hubot-brain properly? You should be running redis, you should have `hubot-redis-brain` in your `package.json` (see [here](https://github.com/techx/hackmit-hackbot/blob/master/package.json#L21) for an example), and you should include `hubot-redis-brain` in your `external-scripts.json` (see [here](https://github.com/techx/hackmit-hackbot/blob/master/external-scripts.json#L7) for an example).

**Comment by anishathalye** [comment]
And if you've done all that and stuff is still going wrong, check the logs, you might find useful information there to help you debug stuff.

**Comment by D0cR3d** [comment]
Here is my package.json: http://pastebin.com/vSQnE0m4
External-Scripts.json: http://pastebin.com/CTtjrzct

I'm using the default setup from your hubot-group. I haven't modified how it tries to save at all. Just installed the hubot-redis-brain and started it up.

**Comment by anishathalye** [comment]
Those look fine. Do you have redis installed? Also, what does the console output say once you start your bot?

**Comment by D0cR3d** [comment]
When I start it this is all the output I get:

C:\DTG_HBot>.\bin\hubot -a slack
[Mon May 23 2016 17:51:54 GMT-0500 (Central Daylight Time)] INFO Connecting...
[Mon May 23 2016 17:51:55 GMT-0500 (Central Daylight Time)] INFO Logged in as dtg_bot of /r/DestinyTheGame, but not yet connected
[Mon May 23 2016 17:51:55 GMT-0500 (Central Daylight Time)] INFO Slack client now connected
[Mon May 23 2016 17:51:55 GMT-0500 (Central Daylight Time)] INFO hubot-redis-brain: Using default redis on localhost:6379

---

redis should be installed as it's logging that it's using the default config url. It basically looks like when it gets to the part of loading the brain it just does nothing. I've added a console.log to that part and it doesn't even attempt to load or create a fresh brain.

**Comment by D0cR3d** [comment]
I started back tracing and it doesn't look like my slack adapter is even loading the brain.

**Comment by anishathalye** [comment]
Weird. Well, it's not an issue with hubot-group, it's something wrong with hubot/brain/redis/something else. Not sure how I can help.
