### ISSUE TITLE
Webpage with group membership info

### ISSUE THREAD

**Issue by defenestration** [anishathalye/hubot-group#9]
I'd like to see a webpage served from hubot that has similar output to the `group dump` command.  Possibly this could be enabled/disabled by an environment option too.

**Comment by anishathalye** [comment]
Ooh, sounds cool! Would you be interested in implementing this? Or are you submitting it as a feature request?

**Comment by defenestration** [comment]
I am working on this and some other features too, will have something up soon!

**Comment by anishathalye** [comment]
Awesome!

**Comment by defenestration** [comment]
Created pr #10 , please check it out!

**Comment by anishathalye** [comment]
(see discussion in #10)
